[package]
authors     = ["Colin Roberts"]
description = "A no-std implementation of the Ajtai commitment scheme."
edition     = "2021"
keywords    = ["cryptography", "commitment scheme", "lattices"]
license     = "MIT"
name        = "ajtai"
readme      = "README.md"
repository  = "https://github.com/autoparallel/ajtai"
version     = "0.1.0"
